version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost # ping on databases and check if it healty or not
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - my_network
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/
    networks:
      - my_network
  wordpress:
    container_name: wordpress
    restart: always
    build: ./requirements/wordpress
    env_file:
      - ./.env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - wp_data:/var/www/

networks:
  my_network:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind